### ISSUE TITLE
App crashed while opening a .mp3 file

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/DialogMusicPlayer#1]
```
FATAL EXCEPTION: Timer-0
Process: phone.vishnu.dialogmusicplayer, PID: 11040
java.lang.IllegalStateException
	at android.media.MediaPlayer.getCurrentPosition(Native Method)
	at phone.vishnu.dialogmusicplayer.MainActivity$a.run(:3)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
FATAL EXCEPTION: main
Process: phone.vishnu.dialogmusicplayer, PID: 11040
java.lang.IllegalStateException
	at android.media.MediaPlayer.getCurrentPosition(Native Method)
	at z1.b.onProgressChanged(:4)
	at android.widget.SeekBar.onProgressRefresh(SeekBar.java:95)
	at android.widget.ProgressBar.doRefreshProgress(ProgressBar.java:1298)
	at android.widget.ProgressBar.-wrap0(Unknown Source:0)
	at android.widget.ProgressBar$RefreshProgressRunnable.run(ProgressBar.java:1245)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by VishnuSanal** [comment]
@shuvashish76 Please test with this [release](https://github.com/VishnuSanal/DialogMusicPlayer/releases/tag/v.1.0.1)

**Comment by shuvashish76** [comment]
Thankyou.
Now working. But after clicking on "Quit" it crashes...

```
FATAL EXCEPTION: Timer-0
Process: phone.vishnu.dialogmusicplayer, PID: 21452
java.lang.IllegalStateException
	at android.media.MediaPlayer.getCurrentPosition(Native Method)
	at phone.vishnu.dialogmusicplayer.MainActivity$a.run(:3)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```
