### ISSUE TITLE
The application closed during a rapid change of speed

### ISSUE THREAD

**Issue by Wjxfi** [VishnuSanal/DialogMusicPlayer#35]
**To Reproduce**
many times quickly press to change the speed

**Expected behavior**
Very fast speed change

**Crash logs**
```
FATAL EXCEPTION: main
Process: phone.vishnu.dialogmusicplayer, PID: 8755
java.lang.IllegalArgumentException
	at android.media.MediaPlayer.setPlaybackParams(Native Method)
	at phone.vishnu.dialogmusicplayer.MainActivity.u(SourceFile:2)
	at h3.d.onClick(Unknown Source:8)
	at android.view.View.performClick(View.java:7753)
	at android.view.View.performClickInternal(View.java:7730)
	at android.view.View.access$3700(View.java:861)
	at android.view.View$PerformClick.run(View.java:29144)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8261)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Smartphone:**
 - by xiaomi
 - Andorid Version: 12, miui 13.0.5
 - App Version: 1.4.1

**Additional context**
I'm hungry

**Comment by VishnuSanal** [comment]
@Wjxfi must be fixed with the latest release [v2.0.0](https://github.com/VishnuSanal/DialogMusicPlayer/releases/tag/v2.0.0), please reopen if it is not the case :)
