### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by shuvashish76** [VishnuSanal/DialogMusicPlayer#43]
**Describe the bug**
DMP crashes when I try to play music 2nd time after playing from another player e.g. VLC

**To Reproduce**
1. Click on your music from any FM > choose DMP
2. Hide the dialog of DMP without closing it i.e while still on the FM screen
3. Click on another music (from FM) > pick a different music player
4. Now again click on a song from FM > choose DMP (while the other music player still playing)
5. See error

**Crash logs**
```
FATAL EXCEPTION: main
Process: phone.vishnu.dialogmusicplayer, PID: 12990
java.lang.IllegalStateException
	at android.media.MediaPlayer._setDataSource(Native Method)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1279)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1260)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1242)
	at android.media.MediaPlayer.attemptDataSource(MediaPlayer.java:1137)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1102)
	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1030)
	at phone.vishnu.dialogmusicplayer.MediaPlaybackService$a.e(SourceFile:18)
	at android.support.v4.media.session.MediaSessionCompat$a$b.onPlayFromUri(SourceFile:16)
	at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1616)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:357)
	at android.app.ActivityThread.main(ActivityThread.java:8090)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
```

**Smartphone (please complete the following information):**
 - Device: moto g71 5G
 - Andorid Version: 12
 - App Version: v2.1.0

**Comment by VishnuSanal** [comment]
btw, thanks for stress testing! just for the record: the crash would have occurred even if DMP was paused.
